"""
Apply Redactions Module

This module handles the final step of applying approved redactions to the PDF.
It downloads the unredacted PDF and the edited redactions JSON, then applies
permanent black boxes using PyMuPDF at the coordinates provided by Nova Pro.

Since coordinates are generated by Nova Pro during the proposal stage and stored
in the redactions JSON as bbox_pts (PDF points, top-left origin), no coordinate
lookup step is needed.

Flow:
1. Download unredacted PDF from S3
2. Download edited-redactions.json from S3
3. Apply black rectangles at bbox_pts coordinates using PyMuPDF
4. Upload redacted PDF to S3
5. Update DynamoDB status to "COMPLETED"
"""

import json
import logging
import os
import time
from typing import Dict, Any, List
import boto3
import fitz  # PyMuPDF

from utils import (
    download_from_s3,
    upload_to_s3,
    update_dynamodb_status
)
from constants import STATUS_APPLYING_REDACTIONS, STATUS_COMPLETED

logger = logging.getLogger()
logger.setLevel(logging.INFO)

_dynamodb = boto3.resource('dynamodb')
_cases_table = _dynamodb.Table(os.environ['DYNAMODB_TABLE_NAME'])

# Small safety expansion applied to every redaction box in PDF points.
# Nova's boxes are already slightly padded per prompt instructions, but this
# provides an additional buffer to ensure no character edges are clipped.
REDACTION_BOX_PADDING_PTS = 2.0


def apply_redactions(case_id: str, s3_paths: Dict[str, str]) -> Dict[str, Any]:
    """
    Apply approved redactions to the PDF using coordinates from Nova Pro.

    Args:
        case_id: Unique case identifier
        s3_paths: Dictionary containing S3 paths for all relevant files

    Returns:
        Dictionary with processing results

    Raises:
        Exception: If any critical step fails
    """
    logger.info(f"Starting redaction application for case: {case_id}")

    update_dynamodb_status(
        case_id=case_id,
        status=STATUS_APPLYING_REDACTIONS,
        metadata={"stage": "starting_redaction_application"}
    )

    try:
        # Step 1: Download unredacted PDF
        logger.info("Downloading unredacted PDF from S3")
        unredacted_pdf_bytes = download_from_s3(s3_paths["unredacted_doc"])

        # Step 2: Download edited redactions JSON
        logger.info("Downloading edited redactions JSON from S3")
        redactions_json_bytes = download_from_s3(s3_paths["edited_redactions"])
        redactions_data = json.loads(redactions_json_bytes.decode('utf-8'))

        redactions = redactions_data.get("redactions", [])
        logger.info(f"Loaded {len(redactions)} approved redactions")

        # Step 3: Apply redactions to PDF
        logger.info("Applying redactions to PDF")
        redacted_pdf_bytes, applied_count, skipped_count = apply_redactions_to_pdf(
            unredacted_pdf_bytes,
            redactions
        )

        if skipped_count > 0:
            logger.warning(
                f"Skipped {skipped_count} redactions due to missing or invalid coordinates. "
                f"These may need to be applied manually."
            )

        # Step 4: Upload redacted PDF to S3
        logger.info("Uploading redacted PDF to S3")
        upload_to_s3(
            s3_path=s3_paths["redacted_doc"],
            data=redacted_pdf_bytes
        )

        # Step 5: Record the redacted doc path in s3_paths so the frontend can find it
        logger.info("Recording redacted_doc path in s3_paths")
        _cases_table.update_item(
            Key={'case_id': case_id},
            UpdateExpression='SET s3_paths.redacted_doc = :path, updated_at = :ts',
            ExpressionAttributeValues={
                ':path': s3_paths["redacted_doc"],
                ':ts': int(time.time()),
            }
        )

        # Step 6: Update DynamoDB status to COMPLETED
        update_dynamodb_status(
            case_id=case_id,
            status=STATUS_COMPLETED,
            metadata={
                "total_redactions_applied": applied_count,
                "total_redactions_skipped": skipped_count,
                "redacted_doc_path": s3_paths["redacted_doc"]
            }
        )

        logger.info(
            f"Successfully completed redaction for case: {case_id}. "
            f"Applied: {applied_count}, Skipped: {skipped_count}"
        )

        return {
            "redactions_applied": applied_count,
            "redactions_skipped": skipped_count,
            "redacted_pdf_path": s3_paths["redacted_doc"]
        }

    except Exception as e:
        logger.error(f"Error applying redactions for case {case_id}: {str(e)}", exc_info=True)
        raise


def apply_redactions_to_pdf(
    pdf_bytes: bytes,
    redactions: List[Dict[str, Any]]
) -> tuple[bytes, int, int]:
    """
    Apply black redaction boxes to the PDF at the coordinates stored in bbox_pts.

    Coordinate system note:
        Nova Pro outputs coordinates in [0, 1000) scale with top-left origin
        (y increases downward). These are converted to PDF points during
        process_document and stored as bbox_pts. PyMuPDF's add_redact_annot
        also accepts rects in top-left origin point space, so no axis
        flip is required — coordinates pass through directly.

    Args:
        pdf_bytes: Raw unredacted PDF bytes
        redactions: List of approved redaction objects, each containing bbox_pts

    Returns:
        Tuple of (redacted_pdf_bytes, applied_count, skipped_count)
    """
    pdf_document = fitz.open(stream=pdf_bytes, filetype="pdf")
    applied_count = 0
    skipped_count = 0

    try:
        # Group redactions by page for efficiency
        redactions_by_page: Dict[int, List[Dict]] = {}
        for redaction in redactions:
            page_num = redaction.get("page")
            if page_num is None:
                logger.warning(f"Redaction missing 'page' field: {redaction.get('text', 'unknown')}, skipping")
                skipped_count += 1
                continue
            if page_num not in redactions_by_page:
                redactions_by_page[page_num] = []
            redactions_by_page[page_num].append(redaction)

        total_pages = len(pdf_document)

        for page_num, page_redactions in redactions_by_page.items():
            # Validate page number is within document bounds
            if page_num < 1 or page_num > total_pages:
                logger.warning(
                    f"Page {page_num} is out of range for this document "
                    f"(total pages: {total_pages}). Skipping {len(page_redactions)} redactions."
                )
                skipped_count += len(page_redactions)
                continue

            # PyMuPDF uses 0-based page indexing
            page = pdf_document[page_num - 1]

            logger.info(f"Applying {len(page_redactions)} redactions to page {page_num}")

            for redaction in page_redactions:
                text = redaction.get("text", "unknown")
                bbox_pts = redaction.get("bbox_pts")

                # Validate bbox_pts exists and has all required keys
                if not bbox_pts:
                    logger.warning(
                        f"Redaction '{text}' on page {page_num} has no bbox_pts, skipping. "
                        f"This redaction may need to be applied manually."
                    )
                    skipped_count += 1
                    continue

                required_keys = ["x0", "y0", "x1", "y1"]
                if not all(k in bbox_pts for k in required_keys):
                    logger.warning(
                        f"Redaction '{text}' on page {page_num} has malformed bbox_pts: "
                        f"{bbox_pts}, skipping."
                    )
                    skipped_count += 1
                    continue

                # Apply safety padding and clamp to page bounds
                page_rect = page.rect
                x0 = max(0, bbox_pts["x0"] - REDACTION_BOX_PADDING_PTS)
                y0 = max(0, bbox_pts["y0"] - REDACTION_BOX_PADDING_PTS)
                x1 = min(page_rect.width,  bbox_pts["x1"] + REDACTION_BOX_PADDING_PTS)
                y1 = min(page_rect.height, bbox_pts["y1"] + REDACTION_BOX_PADDING_PTS)

                rect = fitz.Rect(x0, y0, x1, y1)

                # Sanity check — rect must have positive area
                if rect.is_empty or rect.is_infinite:
                    logger.warning(
                        f"Redaction '{text}' on page {page_num} produced an invalid rect "
                        f"({x0}, {y0}, {x1}, {y1}), skipping."
                    )
                    skipped_count += 1
                    continue

                page.add_redact_annot(rect, fill=(0, 0, 0))
                applied_count += 1
                logger.info(f"Queued redaction: '{text}' at ({x0:.1f}, {y0:.1f}, {x1:.1f}, {y1:.1f})")

            # Apply all queued redactions on this page at once.
            # This permanently removes underlying text and image data within
            # the redaction rectangles — not just a visual overlay.
            page.apply_redactions()
            logger.info(f"Applied all redactions on page {page_num}")

        redacted_pdf_bytes = pdf_document.tobytes(garbage=4, deflate=True)
        return redacted_pdf_bytes, applied_count, skipped_count

    finally:
        pdf_document.close()